apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  namespace: prod
  name: tanzu-app-deploy
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_sub_path
    value: config/dev/tanzu-app-deploy
  source:
    git:
      url: ssh://git@github.com/beeNotice/tanzu-app-deploy.git
      ref:
        branch: main
